### PR TITLE
book: typo fixes in ch06sched/schedule.md

### PR DESCRIPTION
**Pull request by l-qing**
## 说明
修改拼写错误。

## 变化箱单

- 修复了 book/zh-cn/part2runtime/ch06sched/schedule.md 的 typo 错误
- 修复了 book/backlog/sched/exec.md 的 typo 错误
- 修复了 gosrc/runtime/proc.go 的 typo 错误

### CODE REVIEW

**Comment by changkun** [comment]
@yangwenmai will you be available for a review? I am currently on a leave might not be able to read it in detail. Thanks

**Review by yangwenmai — APPROVED** [review]

**Comment by yangwenmai** [comment]
@l-qing please set your correct github config, and rebase your commit message

**Comment by l-qing** [comment]
> @l-qing please set your correct username and email in github config, and rebase your commit message

I rebased the commits.

The username and email address are also confirmed to be correct.

**Comment by yangwenmai** [comment]
image
Looks wrong.

**Comment by l-qing** [comment]
> image
> Looks wrong.

Thanks for the reminder.
I uploaded an avatar for this email at wordpress.com.

This is my email address too.
I checked the `Keep my email addresses private` box in my github settings.
So I had to choose another email to submit.

**Comment by yangwenmai** [comment]
I merged this pr, but your github commit config is not correct.

Because this logo can not to click to your github profile.

**Pull request merged**
